private enum Keywords {
    // create enumeration constants
    IDENTIFIER, FOR, FLOAT, ELSE, IF, INT, WHILE, OPEN_PAREN, 
    CLOSED_PAREN, FLOAT_VALUE, INT_VALUE, UNEQUAL, GREATER, 
    GREATER_OREQUAL, LESS, LESS_OREQUAL, ASSIGN, EQUAL, ADD,
    INCREMENT, ADD_ASSIGN, SUBTRACT, DECREMENT, SUB_ASSIGN, MULTIPLY, MULT_ASSIGN,
    DIVIDE, DIVIDE_ASSIGN, SEMICOLON, OPEN_BRACE, CLOSED_BRACE, EOF
}

public static void main(String[] args) {
}